/* Allegro datafile object indexes, produced by grabber v4.2.1, MinGW32 */
/* Datafile: e:\kingston\sanjay\the choco factory\choco.dat */
/* Date: Sat Nov 01 20:02:02 2014 */
/* Do not hand edit! */

#define 003_BMP                          0        /* BMP  */
#define 003_BMP                          1        /* BMP  */
#define 004_BMP                          2        /* BMP  */
#define 004_BMP                          3        /* BMP  */
#define 005_BMP                          4        /* BMP  */
#define 006_BMP                          5        /* BMP  */
#define 007_BMP                          6        /* BMP  */
#define 008_BMP                          7        /* BMP  */
#define 009_BMP                          8        /* BMP  */
#define 010_BMP                          9        /* BMP  */
#define 011_BMP                          10       /* BMP  */
#define 012_BMP                          11       /* BMP  */
#define 013_BMP                          12       /* BMP  */
#define 014_BMP                          13       /* BMP  */
#define 015_BMP                          14       /* BMP  */
#define 016_BMP                          15       /* BMP  */
#define 017_BMP                          16       /* BMP  */
#define back                             17       /* BMP  */
#define ball                             18       /* BMP  */
#define bulb                             19       /* BMP  */
#define bulbon                           20       /* BMP  */
#define but1                             21       /* BMP  */
#define carrierbot                       22       /* BMP  */
#define drill                            23       /* BMP  */
#define drill2                           24       /* BMP  */
#define drop1                            25       /* BMP  */
#define drop2                            26       /* BMP  */
#define drop3                            27       /* BMP  */
#define drop4                            28       /* BMP  */
#define electric                         29       /* BMP  */
#define end                              30       /* BMP  */
#define endon                            31       /* BMP  */
#define endon1                           32       /* BMP  */
#define endon2                           33       /* BMP  */
#define endon3                           34       /* BMP  */
#define fan                              35       /* BMP  */
#define fan2                             36       /* BMP  */
#define fanon1                           37       /* BMP  */
#define fanon2                           38       /* BMP  */
#define fanon3                           39       /* BMP  */
#define food                             40       /* BMP  */
#define foodlo                           41       /* BMP  */
#define gen                              42       /* BMP  */
#define genon1                           43       /* BMP  */
#define genon2                           44       /* BMP  */
#define genon3                           45       /* BMP  */
#define heater                           46       /* BMP  */
#define heatpower                        47       /* BMP  */
#define hon                              48       /* BMP  */
#define infbulb                          49       /* BMP  */
#define infend                           50       /* BMP  */
#define inffan                           51       /* BMP  */
#define infgen                           52       /* BMP  */

