/* Allegro datafile object indexes, produced by grabber v4.2.1, MinGW32 */
/* Datafile: e:\kingston\sanjay\the choco factory\data.dat */
/* Date: Sat Nov 01 20:07:08 2014 */
/* Do not hand edit! */

#define 003_BMP                          0        /* BMP  */
#define 003_BMP                          1        /* BMP  */
#define 004_BMP                          2        /* BMP  */
#define 004_BMP                          3        /* BMP  */
#define 005_BMP                          4        /* BMP  */
#define 006_BMP                          5        /* BMP  */
#define 007_BMP                          6        /* BMP  */
#define 008_BMP                          7        /* BMP  */
#define 009_BMP                          8        /* BMP  */
#define 010_BMP                          9        /* BMP  */
#define 011_BMP                          10       /* BMP  */
#define 012_BMP                          11       /* BMP  */
#define 013_BMP                          12       /* BMP  */
#define 014_BMP                          13       /* BMP  */
#define 015_BMP                          14       /* BMP  */
#define 016_BMP                          15       /* BMP  */
#define 017_BMP                          16       /* BMP  */
#define back                             17       /* BMP  */
#define ball                             18       /* BMP  */
#define bulb                             19       /* BMP  */
#define bulbon                           20       /* BMP  */
#define but1                             21       /* BMP  */
#define carrierbot                       22       /* BMP  */
#define drill                            23       /* BMP  */
#define drill2                           24       /* BMP  */
#define drop1                            25       /* BMP  */
#define drop2                            26       /* BMP  */
#define drop3                            27       /* BMP  */
#define drop4                            28       /* BMP  */
#define electric                         29       /* BMP  */
#define end                              30       /* BMP  */
#define endon                            31       /* BMP  */
#define endon1                           32       /* BMP  */
#define endon2                           33       /* BMP  */
#define endon3                           34       /* BMP  */
#define fan                              35       /* BMP  */
#define fan2                             36       /* BMP  */
#define fanon1                           37       /* BMP  */
#define fanon2                           38       /* BMP  */
#define fanon3                           39       /* BMP  */
#define food                             40       /* BMP  */
#define foodlo                           41       /* BMP  */
#define gen                              42       /* BMP  */
#define genon1                           43       /* BMP  */
#define genon2                           44       /* BMP  */
#define genon3                           45       /* BMP  */
#define heater                           46       /* BMP  */
#define heatpower                        47       /* BMP  */
#define hon                              48       /* BMP  */
#define infbulb                          49       /* BMP  */
#define infend                           50       /* BMP  */
#define inffan                           51       /* BMP  */
#define infgen                           52       /* BMP  */
#define infkettle                        53       /* BMP  */
#define infmain                          54       /* BMP  */
#define infpuller                        55       /* BMP  */
#define infpusher                        56       /* BMP  */
#define infsolar                         57       /* BMP  */
#define infwall                          58       /* BMP  */
#define intro                            59       /* BMP  */
#define intro2                           60       /* BMP  */
#define kettle                           61       /* BMP  */
#define kettle2                          62       /* BMP  */
#define kon                              63       /* BMP  */
#define l11                              64       /* BMP  */
#define l12                              65       /* BMP  */
#define l13                              66       /* BMP  */
#define l14                              67       /* BMP  */
#define l15                              68       /* BMP  */
#define l16                              69       /* BMP  */
#define l17                              70       /* BMP  */
#define l18                              71       /* BMP  */
#define l21                              72       /* BMP  */
#define l31                              73       /* BMP  */
#define laser                            74       /* BMP  */
#define laser2                           75       /* BMP  */
#define laserre                          76       /* BMP  */
#define level11                          77       /* BMP  */
#define level22                          78       /* BMP  */
#define level33                          79       /* BMP  */
#define level44                          80       /* BMP  */
#define mirdo                            81       /* BMP  */
#define mirdo2                           82       /* BMP  */
#define mirup                            83       /* BMP  */
#define mirup2                           84       /* BMP  */
#define music                            85       /* BMP  */
#define non                              86       /* BMP  */
#define power                            87       /* BMP  */
#define powon                            88       /* BMP  */
#define pullbot                          89       /* BMP  */
#define pullbot2                         90       /* BMP  */
#define pushbot                          91       /* BMP  */
#define pushbot2                         92       /* BMP  */
#define shoot                            93       /* BMP  */
#define shoot2                           94       /* BMP  */
#define solar                            95       /* BMP  */
#define solon                            96       /* BMP  */
#define son                              97       /* BMP  */
#define spring                           98       /* BMP  */
#define spybot                           99       /* BMP  */
#define supply                           100      /* BMP  */
#define t1                               101      /* BMP  */
#define t2                               102      /* BMP  */
#define title                            103      /* BMP  */
#define ton                              104      /* BMP  */
#define truck                            105      /* BMP  */
#define truck2                           106      /* BMP  */
#define von                              107      /* BMP  */
#define wall                             108      /* BMP  */
#define wifir                            109      /* BMP  */
#define wifis                            110      /* BMP  */
#define wiree                            111      /* BMP  */
#define wireh                            112      /* BMP  */
#define wiren                            113      /* BMP  */
#define wires                            114      /* BMP  */

